name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - name: install unzip tool
      run: sudo apt-get install unzip
    - uses: actions/checkout@v2
    - name: Setup Flutter ${{ matrix.flutter-version }}
      uses: DanTup/gh-actions/setup-flutter@master
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
